angular.module('storage', [
    'storage.storageFactory',
    'storage.storageIndexCtrl',
    'storage.storageDivisionCtrl',
    'storage.storageNavigationCtrl',
    'storage.storageBoxDirective',
    'storage.storageBoxHeading',
    'storage.storageBoxCellDirective',
    'storage.storageDivisionDetailsCtrl',
    'storage.storageDivisionFormCtrl',
    'storage.storageFormFactory',
    'storage.storageGridFactory',
    'storage.storageDivisionMoveConfirmCtrl',
    'storage.storageTreeNodeDirective',
    'storage.storageDivisionManager',
    'storage.storageSampleRemoveCtrl',
    'storage.storageSampleMoveCtrl',
    'storage.routes'
]);
